version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing Amazon Corretto JDK 21
      - curl -sL https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.rpm -o corretto.rpm
      - sudo rpm -ivh corretto.rpm
      - java -version
      - echo Installing Maven...
      - yum install -y maven
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests=true

  post_build:
    commands:
      - echo Build successfully completed on `date`

artifacts:
  files:
    - target/blog-backend.jar
  discard-paths: yes
