version: 0.2

phases:
  install:
    commands:
      - echo Installing JDK 21
      - apt-get update
      - apt-get install openjdk-21-jdk
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests=true

  post_build:
    commands:
      - echo Build successfully completed on `date`

artifacts:
  files:
    - target/blog-backend.jar
  discard-paths: yes
