version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre-Build Phase Started...
      - echo Clean and Validate the Maven project
      - mvn clean validate
      - mvn clean install

  build:
    commands:
      - echo Build Phase Started...
      - mvn clean package

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/blog-backend.jar
